### ISSUE TITLE
Lebenslauf anzeigen und bearbeiten können

### ISSUE THREAD

**Issue by LeanderChristmann** [JCNetwork-e-V/androidapp-androidapp#13]
<h3>User Story</h3>
Als JC kann ich in der App meinen Lebenslauf anzeigen lassen und bearbeiten können, damit ich diesen schnell kontrollieren und bearbeiten kann.

<h3>Akzeptanzkriterien</h3>
UI siehe: <a href="https://adobe.ly/30b79TZ">https://adobe.ly/30b79TZ</a>
<br><br>
<ol>
<li>Optimierte (an das Gerät angepasste) Web View vom Lebenslauf ist in der App integriert.</li>
<li>Bearbeitungen werden korrekt gespeichert.</li>
</ol>

**Comment by layla-rohkohl** [comment]
In offline mode, there seems to be an issue with the club into coming up instead.
