### ISSUE TITLE
Sprachsteuerung

### ISSUE THREAD

**Issue by LeanderChristmann** [JCNetwork-e-V/androidapp-androidapp#2]
Luca-Maurice Redmann:
<h3>User Story</h3>
Als JC kann ich die App mit meiner Stimme steuern, um meine Hände nicht verwenden zu müssen.

<h3>Akzeptanzkriterien</h3>
UI siehe: <a href="https://adobe.ly/30b79TZ">https://adobe.ly/30b79TZ</a>
<br><br>
<ol>
<li> Alle Knöpfe sind mit der Stimme bedienbar.</li>
<li>Optional: Integration vom Sprachassistenten ("Wohin muss ich als nächstes",...)</li>
</ol>

**Comment by shockdream6** [comment]
Dismissed. Doesn't help the core strategic goals of this project or not objectively enough. Makes the product not focused enough.
