### ISSUE TITLE
Kontaktliste

### ISSUE THREAD

**Issue by LeanderChristmann** [JCNetwork-e-V/androidapp-androidapp#3]
Luca-Maurice Redmann:
<h3>User Story</h3>
Als JC kann ich mit interessanten Leuten die Kontaktdaten austauschen, um so diese Leute kontaktieren zu können.

<h3>Akzeptanzkriterien</h3>
UI siehe: <a href="https://adobe.ly/30b79TZ">https://adobe.ly/30b79TZ</a>
<br><br>
<ol>
<li>QR-Code Generierung aus Kontaktdaten.</li>
<li>Beim Abscannen wird der Kontakt in den eigenen Kontakten gespeichert (Handy).</li>
</ol>

**Comment by layla-rohkohl** [comment]
My QR Code solves this issue already
